---
- hosts: all
  vars:
  tasks:
  - name: "install clamv"
    apt: name={{ item }} state=latest 
    with_items: 
     - clamav
     - clamav-daemon
     - clamav-freshclam

  - name: "create the check executable"
    copy: content="/usr/bin/freshclam --quiet; /usr/bin/clamscan --recursive --no-summary --infected / 2>/dev/null" dest=/root/clamv_check.sh mode=0700

  - name: "run the check"
    shell: /root/clamv_check.sh >> somelog.txt
    args:
     warn: False 
