---
# tasks file for rhevm
 - get_url: url={{ OvirtPackage }}  dest=/tmp/{{ OvirtReleaseRpm }} mode=0440
 - yum: name=/tmp/{{ OvirtReleaseRpm }} state=installed
 - yum: name={{ item }} state=installed
   with_items:
    - ovirt-hosted-engine-setup 
    - screen 
    - glusterfs-server 
    - nfs-utils 
    - vdsm-gluster 
    - system-storage-manager
   register: rebootit
 - name: reboot the system
   shell: reboot 
   async: 0
   poll: 0
   ignore_errors: true
   when: rebootit.changed
 - name: wait for ssh to come back up
   local_action: wait_for host={{ ansible_fqdn }} port=22 delay=180 timeout=900 state=started
 
